{% set name = "pyodbc" %}
{% set version = "5.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03d7d0b04d5a9156099ce8d03e92f3956783746fa9234eb6f5b5cfc12b645011
  patches:
    - 0001-Add-sys.prefix-include-to-include_dirs.patch  # [unix]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - unixodbc   # [unix]
  run:
    - python

test:
  imports:
    - pyodbc

about:
  home: https://github.com/mkleehammer/pyodbc
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: DB API Module for ODBC
  description: |
    pyodbc is a Python DB API 2 module for ODBC. This project provides an
    up-to-date, convenient interface to ODBC using native data types like
    datetime and decimal.
  doc_url: http://mkleehammer.github.io/pyodbc/
  doc_source_url: https://github.com/mkleehammer/pyodbc/blob/master/docs/index.md
  dev_url: https://github.com/mkleehammer/pyodbc

extra:
  recipe-maintainers:
    - nehaljwani
    - xhochy
