travis:
  secure:
    BINSTAR_TOKEN: rH/SlrZHCleOsksW3nLT1IuI5UFkKxLPeiNWx9ED6AR2/nAE2j5Vgbd2tLg327UZy1gmu8vVT91DozH0FNMuDNziFNBjXyIAovdIKhdc8vOCFtCoOqJzXl8MFFv2Trto6pXH8S1GFGfLd2/Tk8cBJd7r3yR2TxJDIBoM9SVhIlAtK2atRjlM3YNNV/UeaOS+15W/giMRUGx34Igoo/1LQm3djv+nV8Db0VYz6k0V2QfGTvs59aCp3PkEypw7Kpo7EDBKHrKPk01Fe4VBkAEG6kMnSbp7VrSuErWoEGRaNZhKs3b3uDILG+sIh96T9szaR62ZG6ps+BVHSnnZjNrS96enCoxvumgqe3bcGttUh14xawAx/PaaOjMB/qF1M5WkUIvIDPn/o6+MIQgy9I/uypM/PteevxlH+iq/4MMIPC2P+RWsMFMnK/e8LibTVAGvn959pgN+UQJzTrlBQ99lEnaY1OlvKxzFNyFC7+nAXp3JN9w9FR8/NmaTHy3a1KCylwI+8ELvJ0/0a/JuT9GDq2tPYFmA6Fn8IS/03JvMXVI2dhl8zMN2FfpPDv0hYpd1QaFhY/UwLX/nDs3rthIN7ploP0N8nV2nNyCchJCEnLR0eEMvjyaYR+oXKl68zKOtNtNI4QdUduncv3gi5TTaxRTtZtjBMzcqu7cCHoQxc8o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
